name: manually build gmake for linux-aarch64

on:
  workflow_dispatch:

jobs:

  linux-aarch64:

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          run chmod a+x ppkg
          run ./ppkg setup --use-system-package-manager
          run ./ppkg update
          run ./ppkg install gmake --link-type=static-only --install-lib=static
          run ./ppkg pack    gmake

          ls ~/.ppkg/packed/gmake-*.tar.xz > filepath.txt
          EOF

          chmod +x run.sh

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v $PWD:$PWD -w $PWD --name alpine arm64v8/alpine sh run.sh
      - run: docker cp alpine:$(cat filepath.txt) .

      - run: ls

      - uses: actions/upload-artifact@v3
        with:
          name: gmake---linux-aarch64-tar-xz
          path: gmake-*-linux-aarch64.tar.xz
